/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [{
        _id: 'Wo5dMEP_BbI',
        title: 'Almost Home | Lunar Revel 2022 Cinematic Trailer - League of Legends: Wild Rift',
        description: 'Dive into Wild Rift: the skills-and-strats 5v5 MOBA experience of League of Legends, now built from the ground up for mobile and console. With fresh controls and fast-paced games, players of every level can team up with friends, lock in their champion, and go for the big plays.',
        creator: 'League of Legends: Wild Rift',
        views: '1.7M',
        duration: '2:49',
        thumbnail: 'https://staticg.sportskeeda.com/editor/2022/01/13e9a-16426623996045-1920.jpg',
        alt: 'Almost Home Trailer',
        category: 'Strategy',
        avatar: 'https://yt3.ggpht.com/hUdAfgjAm54AGonQSzY52CfkDce84JwBJtOmbxue8vr5Zcv2pFgNBW_yGCGk5ofU0ecnQ4lpuA=s68-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/pCjFpGgFZlc',
    },
    {
        _id: 'F_Riqjdh2oM',
        title: 'Max Payne 3 - Official Launch Trailer',
        description: 'For Max Payne, the tragedies that took his loved ones years ago are wounds that refuse to heal. No longer a cop, close to washed up and addicted to pain killers, Max takes a job in São Paulo, Brazil, protecting the family of wealthy real estate mogul Rodrigo Branco, in an effort to finally escape his troubled past. But as events spiral out of his control, Max Payne finds himself alone on the streets of an unfamiliar city, desperately searching for the truth and fighting for a way out.',
        creator: 'Rockstar Games',
        views: '1.4M',
        duration: '1:37',
        thumbnail: 'http://i.imgur.com/YAlAG.jpg',
        alt: 'May Payne 3 Trailer',
        category: 'Action',
        avatar: 'https://yt3.ggpht.com/r7mISTzNbcLem_plduc_SKMh9KUiP8CWnuhS7H4-CCErF4juXxkrK-5_4LOIMeYl-lXAXMUG=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/4Uc_dbG7MR8',
    },
    {
        _id: 'Y_Qwqjdxyoa',
        title: 'Grand Theft Auto V Trailer',
        description: 'Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the seventh main entry in the Grand Theft Auto series, following 2008`s Grand Theft Auto IV, and the fifteenth instalment overall',
        creator: 'Rockstar Games',
        views: '81M',
        duration: '1:24',
        thumbnail: 'https://www.dexerto.com/wp-content/uploads/2021/05/17/gta-v-speedrun-no-damage-taken-complete.jpg',
        alt: 'Grand Theft Auto V',
        category: 'Arcade',
        avatar: 'https://yt3.ggpht.com/r7mISTzNbcLem_plduc_SKMh9KUiP8CWnuhS7H4-CCErF4juXxkrK-5_4LOIMeYl-lXAXMUG=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/QkkoHAzjnUs',
    },
    {
        _id: 'Uohxqpoxyoa',
        title: 'Official Call of Duty®: Modern Warfare® Remastered – Launch Trailer',
        description: 'Call of Duty: Modern Warfare Remastered is a 2016 first-person shooter game developed by Raven Software and published by Activision.',
        creator: 'Call of Duty',
        views: '2.9M',
        duration: '2:03',
        thumbnail: 'https://i.gadgets360cdn.com/large/codmwr_1475657665559.jpeg',
        alt: 'Call of Duty Modern Warfare',
        category: 'Action',
        avatar: 'https://yt3.ggpht.com/JqJzxIWIummbTfKAs9z_kh0LbvYEmSqDce1uiIeg-XJYh-FgYuDsxM4I3aQI-LQczAYgrPCzGQ=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/l-eMi1xJ2dM',
    },
    {
        _id: 'Ophxqppcimv',
        title: 'Dota 2 Gamescom Trailer',
        description: 'Dota 2 is a multiplayer online battle arena video game developed and published by Valve. The game is a sequel to Defense of the Ancients, which was a community-created mod for Blizzard Entertainment`s Warcraft III: Reign of Chaos.',
        creator: 'dota2',
        views: '11M',
        duration: '1:55',
        thumbnail: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg?t=1650611880',
        alt: 'Dota 2',
        category: 'Strategy',
        avatar: 'https://yt3.ggpht.com/ytc/AKedOLQ_luS48R-_G0x8dgpPpT_-_ciQ1dhCs9-175_vNQ=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/-cSFPIwMEq4',
    },
    {
        _id: 'Rglxo_hjczqb',
        title: 'The Legend Of The Ice Hound (Clash Of Clans)',
        description: 'Clash of Clans is a 2012 free-to-play mobile strategy video game developed and published by Finnish game developer Supercell. The game was released for iOS platforms on August 2, 2012, and on Google Play for Android on October 7, 2013.',
        creator: 'Clash of Clans',
        views: '10M',
        duration: '1:37',
        thumbnail: 'https://images.fanpedia.com/resize/3/2020-ice-hound-01.533x300q15.jpg.webp',
        alt: 'Clash of Clans',
        category: 'Strategy',
        avatar: 'https://yt3.ggpht.com/mw5amBP49SqVDUr1wCgcGsaq2YvnFqGVC09b4u2FzX9z12tSKvqSqRVgJSMYW5cJnyuDLdh3tIo=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/_CPrYB6Q-HM',
    },
    {
        _id: 'lvwio_oabfbyb',
        title: 'FIFA 18 El Tornado - More Than a Game - Official Trailer',
        description: 'From in the game to on the pitch then across the globe, watch FIFA 18 cover star Cristiano Ronaldo, Antoine Griezmann, Dele Alli, and James Harden put their spin on, El Tornado, the latest skill move from The World’s Game. ',
        creator: 'EA SPORTS FIFA',
        views: '7.1M',
        duration: '2:21',
        thumbnail: 'https://i.guim.co.uk/img/media/2a9d099cd2f08d435181960d11219716b22a6e77/88_0_1312_788/master/1312.jpg?width=1200&quality=85&auto=format&fit=max&s=bb55cce175b93dcc6f00442079388927',
        alt: 'Fifa 18',
        category: 'Sports',
        avatar: 'https://yt3.ggpht.com/i4uZVgz4ARXHsZwr_zcvgpTxTHctNpWLAaGFBw-Hewezq-pgc4vfCOuF8SpHQM7L-_O0fLNPQQ=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/pjR51wO7vII',
    },
    {
        _id: 'pabwubyuwblyb',
        title: 'Valorant - Official Cinematic Launch Trailer',
        description: 'VALORANT, the 5v5 character-based tactical shooter from Riot Games is free to download and play ',
        creator: 'GameSpot Trailers',
        views: '250K',
        duration: '2:13',
        thumbnail: 'https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/EGS_VALORANT_RiotGames_S1_2560x1440-160cacc798ef1693cc0a339e869f1761',
        alt: 'Valorant',
        category: 'Sports',
        avatar: 'https://yt3.ggpht.com/ytc/AKedOLTKNngxaM5Zld7O1htVPvBVLPQXExkTtw_Hsjfcww=s88-c-k-c0x00ffffff-no-rj',
        link: 'https://www.youtube.com/embed/lWr6dhTcu-E',
    },
]